[package]
name = "ffmpeg_converter"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "*"
anyhow = "*"
num_cpus = "*"
pathdiff = "*"
clap = { version = "*", features = ["derive", "cargo"] }