[package]
name = "ffmpeg_converter"
version = "2.0.0"
edition = "2021"

[[bin]]
name = "cv"
path = "src/main.rs"

[dependencies]
ignore = "0.4"
anyhow = "1.0"
num_cpus = "1.14"
pathdiff = "0.2"
clap = { version = "4.0", features = ["derive"] }
