[package]
name = "ffmpeg_converter"
version = "1.1.0"
edition = "2021"

[[bin]]
name = "cv"
path = "src/main.rs"

[dependencies]
ignore = "*"
anyhow = "*"
num_cpus = "*"
pathdiff = "*"
clap = { version = "*", features = ["derive", "cargo"] }